# This file is used within Dockerfile.
# It makes NGINX being able to recognize Angular-style routing correctly.
# I don't need to update it if my routes changes because it already takes into account any kind of routes.

server {
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Ensures any route not matching a real file goes to index.html.
        try_files $uri $uri/ /index.html;
    }
}
